name: "lorem"
description: "lorem"
author: "TrustMe.ai"

# inputs:
#   host:
#     description: "SSH host address."
#     default: localhost

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  # using: "composite"
  # steps:
  #   - name: Set GitHub Path
  #     run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
  #     shell: bash
  #     env:
  #       GITHUB_ACTION_PATH: ${{ github.action_path }}
  #   - name: Run entrypoint.sh
  #     run: entrypoint.sh
  #     shell: bash
  #     env:
  #       INPUT_HOST: ${{ inputs.host }}
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}


branding:
  icon: "terminal"
  color: "gray-dark"