name: "lorem"
description: "lorem"
author: "TrustMe.ai"

# inputs:
#   host:
#     description: "SSH host address."
#     default: localhost

inputs:
  path:
    description: "Path to the code"
    required: false
    default: "${{ github.workspace }}" # Set default to the workspace path
  fail-if-high-more-than:
    description: "fail if high vulnerability is more than a specific limit"
    required: false
    default: '0' # Set default to the workspace path
  fail-if-medium-more-than:
    description: "fail if medium vulnerability is more than a specific limit"
    required: false
    default: '0' # Set default to the workspace path
  fail-if-low-more-than:
    description: "fail if low vulnerability is more than a specific limit (must be an integer)."
    required: false
    default: '0' # Set default to the workspace path


runs:
  # using: "composite"
  # steps:
  #   - name: Set GitHub Path
  #     run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
  #     shell: bash
  #     env:
  #       GITHUB_ACTION_PATH: ${{ github.action_path }}
  #   - name: Run entrypoint.sh
  #     run: entrypoint.sh
  #     shell: bash
  #     env:
  #       INPUT_HOST: ${{ inputs.host }}
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.fail-if-high-more-than }}
    - ${{ inputs.fail-if-medium-more-than }}
    - ${{ inputs.fail-if-low-more-than }}



branding:
  icon: "terminal"
  color: "gray-dark"
