name: "lorem"
description: "lorem"
author: "TrustMe.ai"

inputs:
  path:
    description: "Path to the code"
    required: false
    default: "${{ github.workspace }}" # Set default to the workspace path
  fail-if-high-more-than:
    description: "fail if high vulnerability is more than a specific limit (must be an integer)."
    required: false
    default: '0'
  fail-if-medium-more-than:
    description: "fail if medium vulnerability is more than a specific limit (must be an integer)."
    required: false
    default: '0'
  fail-if-low-more-than:
    description: "fail if low vulnerability is more than a specific limit (must be an integer)."
    required: false
    default: '0'
  token:
    description: "fail if low vulnerability is more than a specific limit (must be an integer)."
    required: false
  langs:
    description: "fail if low vulnerability is more than a specific limit (must be an integer)."
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  # image: 'docker://ghcr.io/trustme-ai/test-trustme-plugin:2.6.0.13'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.fail-if-high-more-than }}
    - ${{ inputs.fail-if-medium-more-than }}
    - ${{ inputs.fail-if-low-more-than }}
    - ${{ inputs.token }}
    - ${{ inputs.langs }}

branding:
  icon: "terminal"
  color: "gray-dark"
